courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('details/', views.course_details, name='course_details'),
    path('details/new_exam/', views.new_exam, name='new_exam'),
]

grading/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'grading'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('', include('login.urls')),
    # path('courses/', include('courses.urls')),
    # path('results/', include('results.urls')),
    # path('login/', include('login.urls')),
    # path('', views.homepage, name='homepage'),

]

login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('teacher/login/', views.login_teacher),
    path('student/login/', views.login_student),
    path('teacher/dashboard/', views.teacher_dashboard),

    path('teacher/dashboard/<int:subject_id>/',
         views.course_detail, name='course_detail'),

    path('teacher/dashboard/<int:subject_id>/create_exam/',
         views.create_exam, name='create_exam'),

    path('teacher/dashboard/<int:subject_id>/create_exam/<int:exam_id>/create_set/',
         views.create_set, name='create_set'),

    path('teacher/dashboard/<int:subject_id>/<int:exam_id>',
         views.exam_detail, name='exam_detail'),

    path('student/dashboard/<int:subject_id>/<int:exam_id>/take_exam',
         views.take_exam, name='take_exam'),
    #     result
    path('student/dashboard/<int:subject_id>/<int:exam_id>/result',
         views.st_result, name='st_result'),

    path('student/dashboard/<int:subject_id>/<int:exam_id>',
         views.st_exam_detail, name='st_exam_detail'),

    path('teacher/dashboard/<int:subject_id>/<int:exam_id>/teacher_result',
         views.teacher_result, name='teacher_result'),
    #     path('teacher/dashboard/<int:subject_id>/create_exam/exam_created',
    #          views.exam_created, name='exam_created'),

    path('student/dashboard/', views.student_dashboard),
    path('student/dashboard/<int:subject_id>/',
         views.st_course_detail, name='st_course_detail'),

    path('logout_user/', views.logout_user, name="logout_user"),
    path('results/', include('results.urls')),


]

courses/models.py
from django.db import models

# Create your models here.


class subject(models.Model):
    subject_name = models.CharField(max_length=100)

courses/views.py
from django.shortcuts import render
from django.http import HttpResponse


def course_list(request):
    return render(request, 'courses/course_list.html')


def course_details(request):
    return render(request, 'courses/course_details.html')


def new_exam(request):
    return render(request, 'courses/new_exam.html')

courses/templates/courses/course_details.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  {{ sub.0.subject_name }}
</p>




<p class="display-5 text-info pt-2">Exam List</p>
<hr>
{% if xms %}
<ul class="list-group">
  {% for exam in xms %}
  <li class="list-group-item list-group-item-light fw-bold">
    <a
    class="text-primary"
      href="http://127.0.0.1:8000/teacher/dashboard/{{sub.0.subject_id}}/{{exam.exam_id}}"
      >{{ exam.exam_name }}</a
    >
  </li>
  <br />

  {% endfor %} {% else %}
  <div class="fs-4">There is no exam for this subject!</div>
  {% endif %}
</ul>
<button type="button" class="btn btn-info btn-lg text-light">
  <a href="{% url 'login:create_exam' subject_id=subject_id %}"
    >Create New Exam</a
  >
</button>
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base_layout.html' %} {% block content %}
<style>
  .container {
    top: 0;
    left: 0;
    position: relative;
    transform: translate(0%, 0%);
  }
</style>
<div class="head d-flex justify-content-between"style="border-bottom: 1px solid rgb(205, 231, 241)">
<p
  class="display-4 text-primary"
  
>
  Teacher Dashboard
</p>
<form action={% url "login:logout_user" %} method="POST">
  {% csrf_token %}  
 <br>
  <input class="btn btn-danger float-sm-end" type="submit" value="logout" > 
  <br>
</form>
</div>
<br>
<div class="row justify-content-center">
  {% for sub in subs %}
  <div class="col-md-4 col-sm-6 p-1">
    <div class="card">
      {% load static %}
      <img
        class="card-img-top img-fluid"
        src="{% static 'img/bg.png'%}"
        alt="Card image"
      />
      <div class="card-body">
        <p class="card-title h4">{{ sub.subject_id }}.&nbsp;{{ sub.subject_name }}</p>

        <a href="{% url 'login:course_detail' subject_id=sub.subject_id %}" class="btn btn-primary"
          >Details
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<br />
{% endblock %}

courses/templates/courses/create_set.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary pb-1"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Question Set Creation
</p>
<form
  class="form-control"
  name="exam"
  method="POST"
  action="{% url 'login:create_set' subject_id=subject_id exam_id=exam_id %}"
>
  {% csrf_token %}
  <label class="py-1" for="set_id">Set ID:</label>
  <input class="form-control" type="text" name="set_id" id="set_id" />
  <label class="py-1" for="set_number">Set Numebr(1,2,3) :</label>
  <input class="form-control" type="text" name="set_number" id="set_number" />
  <button
    type="submit"
    class="btn btn-outline-primary btn-lg mt-5 float-sm-end"
    id="save-btn"
  >
    Submit
  </button>
  <br />
  {% endblock %}
</form>

courses/templates/courses/exam_created.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Exam created!
</p>

{% endblock %}

courses/templates/courses/exam_detail.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Exam Details
</p>


<div class="btn btn-outline-primary">See Result</div>

{% endblock %}

courses/templates/courses/new_exam.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary pb-1"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Exam Creation
</p>
<form
  class="form-control"
  name="exam"
  method="POST"
  action="{% url 'login:create_exam' subject_id=subject_id%}"
>
  {% csrf_token %}
  <label class="py-1" for="exam_id">Exam ID:</label>
  <input class="form-control" type="text" name="exam_id" id="exam_id" />
  <label class="py-1" for="exam_name">Exam name:</label>
  <input class="form-control" type="text" name="exam_name" id="exam_name" />
  <!-- <label class="py-1" for="set_number">Question Set Number(1,2,3):</label>
  <input class="form-control" type="text" name="set_number" id="set_number" /> -->
  <button
    type="submit"
    class="btn btn-outline-primary btn-lg mt-5 float-sm-end"
    id="save-btn"
  >
    Submit
  </button>
  <br />
  <!--   
  <p class="fs-3 text-info">Select Subject:</p>
  <select
    class="form-select form-select-lg form-control mb-3"
    name="subjects"
    id="subjects"
    type="text"
    aria-label=".form-select-lg example"
  >
    <option selected>Select Subject</option>
    <option value="1">Computer Security</option>
    <option value="2">Computer Architecture</option>
    <option value="3">Computer Networks</option>
  </select>
  <p class="fs-3 text-info">Select Set Number:</p>
  <select
    class="form-select form-select-lg form-control mb-3"
    name="subjects"
    id="subjects"
    type="text"
    aria-label=".form-select-lg example"
  >
    <option selected>Select Set Number</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
  </select>
</form> -->
  {% endblock %}
</form>

courses/templates/courses/st_course_details.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  {{sub.0.subject_name}}
</p>



<p class="display-5  text-info pt-2">Exam List</p>
{% if xms %}
<ul class="list-group">
  {% for exam in xms %}
  <li class="list-group-item list-group-item-light fs-5 fw-bold">
    <a
    class="text-primary"
      href="http://127.0.0.1:8000/student/dashboard/{{sub.0.subject_id}}/{{exam.exam_id}}"
      >{{ exam.exam_name }}</a
    >
  </li>
  <br />

  {% endfor %} {% else %}
  <div class="fs-4">There is no exam for this subject!</div>
  {% endif %}
</ul>
{% endblock %}

courses/templates/courses/st_course_list.html
{% extends 'base_layout.html' %} {% block content %}
<style>
  .container {
    top: 0;
    left: 0;
    position: relative;
    transform: translate(0%, 0%);
  }
</style>
<div class="head d-flex justify-content-between"style="border-bottom: 1px solid rgb(205, 231, 241)">
<p
  class="display-2 text-primary"
  
>
Welcome {{ uname }}

</p>
<form action={% url "login:logout_user" %} method="POST">
  {% csrf_token %}  
 <br>
  <input class="btn btn-danger float-sm-end" type="submit" value="logout" > 
  <br>
</form>
</div>
<br>
<div class="row justify-content-center">
  {% for sub in subs %}
  <div class="col-md-4 col-sm-6 p-1">
    <div class="card">
      {% load static %}
      <img
        class="card-img-top img-fluid"
        
        src="{% static 'img/bg.png'%}"
        alt="Card image"
      /><!-- src="https://img.freepik.com/premium-photo/abstract-painting-color-texture-modern-futuristic-pattern-loseup-painting-colorful-background_88135-37873.jpg?w=826" -->
      <div class="card-body">
        <h4 class="card-title">{{ sub.subject_name }}</h4>

        <a href="{% url 'login:st_course_detail' subject_id=sub.subject_id %}" class="btn btn-primary"
          >Details
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<br />
{% endblock %}

courses/templates/courses/st_exam_detail.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Exam Details
</p>
<div class="btn btn-primary">
  <a class="text-white" href="{% url 'login:take_exam' subject_id=subject_id exam_id=exam_id%}"
    >Take Exam</a
  ></div>

  <br />
  <br />

  <div class="btn btn-outline-success">See Result</div>

  {% endblock %}
</div>

courses/templates/courses/st_result.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary pb-1"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  Student Result
</p>
<!-- score_list.html -->

<div class="h1">Scores</div>
<ul>
  {% for score in scores %}
  <li>
    Score: {{ score.score }} Question: {{ score.question_id }} User: {{
    score.user_id }}
  </li>
  {% empty %}
  <li>No scores found.</li>
  {% endfor %}
</ul>

{% endblock %}

courses/templates/courses/t_result.html
{% extends 'base_layout.html' %} {% block content %}
<p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  All Students result
</p>


<table class="table table-info table-hover " style="border-radius: 1.5rem;">
  <thead>
    <tr>
      
      <th scope="col">Student ID</th>
      <th scope="col">Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{  }}</th>
      <td>{{ score}}</td>
      
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>{{ score}}</td>
      
    </tr>
   
  </tbody>
</table>

{% endblock %}

courses/templates/courses/take_exam.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}
<p
  class="display-4 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>{{ sub.0.subject_name}} 
  
</p>

<div class="fs-5 text-info">Exam Name:&nbsp;&nbsp;<span class="fst-italic">{{xm.0.exam_name}}</span> &nbsp; <br> Set Number:<span class="fst-italic"> {{ ques_set.0.set_number }}</span> <br> Student Name: &nbsp;{{user_name}} </div>
<br>
<form
  class="form-control"
  name="exam"
  method="POST"
  action="{% url 'login:take_exam' subject_id=subject_id exam_id=exam_id %}"
>

  {% csrf_token %} 
   <!-- for question in ques -->
  <label class="py-1" for="res_text1">{{ ques.0.question_text }}</label>
  <textarea class="form-control" id="res_text" name="res_text1" rows="3"></textarea>

  <label class="py-1" for="res_text2">{{ ques.1.question_text }}</label>
  <textarea class="form-control" id="res_text" name="res_text2" rows="3"></textarea>


   <!-- comment % Increment the counter variable 'i' % endcomment % -->
   <!-- with forloop.counter as i  -->

   <!-- endwith  -->

 <!-- endfor  -->
  <button
    type="submit"
    class="btn btn-outline-primary btn-lg mt-5 float-sm-end"
    id="save-btn"
  >
    Submit
  </button>
  <br />
  

  {%endblock%}
</form>