grading/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'grading'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('', include('login.urls')),
    # path('courses/', include('courses.urls')),
    # path('results/', include('results.urls')),
    # path('login/', include('login.urls')),
    # path('', views.homepage, name='homepage'),

]

login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('teacher/login/', views.login_teacher),
    path('student/login/', views.login_student),
    path('teacher/dashboard/', views.teacher_dashboard),

    path('teacher/dashboard/<int:subject_id>/',
         views.course_detail, name='course_detail'),

    path('teacher/dashboard/<int:subject_id>/create_exam/',
         views.create_exam, name='create_exam'),

    path('teacher/dashboard/<int:subject_id>/create_exam/<int:exam_id>/create_set/',
         views.create_set, name='create_set'),

    path('teacher/dashboard/<int:subject_id>/<int:exam_id>',
         views.exam_detail, name='exam_detail'),

    path('student/dashboard/<int:subject_id>/<int:exam_id>/take_exam',
         views.take_exam, name='take_exam'),
    #     result
    path('student/dashboard/<int:subject_id>/<int:exam_id>/result',
         views.st_result, name='st_result'),

    path('student/dashboard/<int:subject_id>/<int:exam_id>',
         views.st_exam_detail, name='st_exam_detail'),

    path('teacher/dashboard/<int:subject_id>/<int:exam_id>/teacher_result',
         views.teacher_result, name='teacher_result'),
    #     path('teacher/dashboard/<int:subject_id>/create_exam/exam_created',
    #          views.exam_created, name='exam_created'),

    path('student/dashboard/', views.student_dashboard),
    path('student/dashboard/<int:subject_id>/',
         views.st_course_detail, name='st_course_detail'),

    path('logout_user/', views.logout_user, name="logout_user"),
    path('results/', include('results.urls')),


]

templates/about.html
{% extends 'base_layout.html' %} {% block content %}
<!-- <p
  class="display-2 text-primary"
  style="border-bottom: 1px solid rgb(205, 231, 241)"
>
  About Us
</p> -->
<p class="h1 text-center text-primary">Student Grading Using Text Similarity</p>
<p class="text-center fs-3 text-info">By 
  <ul class="list-unstyled text-center lead">
    <li>Tishme Hasan</li>
    <li>Amanta Hossain</li>
    <li>Md Abir Reza Pial</li>
    <li>Md Mahmudul Hasan</li>
    <li>Md Zishan Mahmud</li>
  </ul>
</p>
<hr/>
<p class="text-dark ">

Text similarity measurement is one of the most important issues in the current world. We are continually working to enhance our system to reduce human error while achiev- ing high accuracy, and a written answer test—a form of assessment in which no response alternatives are offered and which is designed to gauge student’s level of topic understand- ing—is being employed to achieve this goal. Manually evaluating the quality of the answers is a subjective and time-consuming operation. The purpose of this research is to create a text similarity system that will enable teachers to evaluate a script by comparing it to a sample response saved in the system to provide an automated approach of evaluating text responses based on Jaro-Winkler. The calculated results are in real time to a remote server, the results in this case must be relevant and obtained very quickly. The objective is to not only shorten the time and eliminate any risk of biasness but also explores the potential of text similarity-based grading to improve the grading process.
</p>
<p class="badge bg-primary text-wrap text-center">©Team Corpus | 2023</p>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Student Grading Using Text Similarity</title>
    <style>
      @media screen and (min-width: 992px) {
        .container {
          background-color: azure;
          border-radius: 2em;
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
        }
      }
      a {
        text-decoration: none;
        color: white;
      }
      .container {
        /* background-color: azure; */
        /* background-color: #e0eff1; */
        /* border-radius: 2em;
        box-shadow: 0px 10px 15px -3px rgba(0,0,0,0.1); */
        backdrop-filter: blur(22px) saturate(200%);
        -webkit-backdrop-filter: blur(22px) saturate(140%);
        background-color: rgba(254, 254, 254, 0.73);
        border-radius: 2rem;
        border: 1px solid rgba(209, 213, 219, 0.3);

        /* top: 0;
    left: 0;
    position: relative;
    transform: translate(0%, 0%); */
        /* height: 80vh; */
      }

      body {
        height: 110vh;

        background: rgb(209, 244, 244);
        background: -moz-linear-gradient(
          315deg,
          rgba(209, 244, 244, 1) 40%,
          rgba(209, 244, 234, 1) 67%,
          rgba(209, 241, 244, 1) 91%
        );
        background: -webkit-linear-gradient(
          315deg,
          rgba(209, 244, 244, 1) 40%,
          rgba(209, 244, 234, 1) 67%,
          rgba(209, 241, 244, 1) 91%
        );
        background: linear-gradient(
          315deg,
          rgba(209, 244, 244, 1) 40%,
          rgba(209, 244, 234, 1) 67%,
          rgba(209, 241, 244, 1) 91%
        );
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#d1f4f4",endColorstr="#d1f1f4",GradientType=1);

        background-size: cover;
        /* background-color: rgb(209, 244, 244); */
        /* background: rgb(235,244,245);
background: linear-gradient(90deg, rgba(235,244,245,1) 0%, rgba(235,244,245,1) 23%, rgba(208,221,235,1) 74%); */
      }

      .card.bg-transparent {
        background-color: transparent;
        border: 1px solid rgba(255, 253, 253, 0.773);
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'login:homepage' %}">
          <img class="w-50" src="{% static 'img/logo.png' %}" alt="My image"
        /></a>
      </div>
    </nav>
    <div class="container p-3">{% block content %} {% endblock %}</div>
  </body>
</html>

templates/homepage.html
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <title>Automated Grading</title>
  </head>
  <body>
    <p class="display-1 text-primary">New Homepage</p>
  </body>
</html> -->

{% extends 'base_layout.html' %} {% block content %}
<h1>Homepage</h1>

{% endblock %}